
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author USER
 */
public class editpatientdetail extends javax.swing.JFrame {

    /**
     * Creates new form 
     */
    public editpatientdetail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf3 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        tf5 = new javax.swing.JTextField();
        tf6 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf7 = new javax.swing.JTextField();
        tf8 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edi2.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("DELETE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 152, 50));

        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 152, 50));

        jButton3.setText("RESET");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 550, 160, 60));

        jButton4.setForeground(new java.awt.Color(0, 0, 255));
        jButton4.setText("BACK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 550, 180, 60));

        jButton6.setText("SEARCH");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 152, 50));
        getContentPane().add(tf1, new org.netbeans.lib.awtextra.AbsoluteConstraints(257, 43, 180, 40));

        tf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf2ActionPerformed(evt);
            }
        });
        getContentPane().add(tf2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 180, 40));
        getContentPane().add(tf3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 154, 180, 50));
        getContentPane().add(tf4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 180, 50));
        getContentPane().add(tf5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 470, 50));

        tf6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf6ActionPerformed(evt);
            }
        });
        getContentPane().add(tf6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 180, 40));

        jLabel1.setText("PATIENT NAME");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 103, -1, -1));

        jLabel2.setText("PATIENT AGE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        jLabel3.setText("BLOOD GROUP");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 490, -1, -1));

        jLabel4.setText("FATHER NAME");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, -1, -1));

        jLabel5.setText("LOCAL ADDRESS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, -1, -1));

        jLabel6.setText("CITY");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, -1, -1));
        getContentPane().add(tf7, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 405, 180, 40));

        tf8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf8ActionPerformed(evt);
            }
        });
        getContentPane().add(tf8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 470, 180, 50));

        jLabel7.setText("ENTER PATIENT ID");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 50, -1, -1));

        jLabel8.setText("CONTACT NO");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setText("EDIT PATIENT DETAIL");
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 140, 30));

        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 60, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/edi2.jpg"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        tf3.setText(null);
        tf4.setText(null);
        tf5.setText(null);
        tf2.setText(null);
        tf6.setText(null);
        tf7.setText(null);
        tf8.setText(null);
               // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void tf8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
  new User().setVisible(true);
this.setVisible(false);       // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void tf6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

 int ans=JOptionPane.showConfirmDialog(this,"Do you surely want to update this record?");
if(ans==JOptionPane.YES_OPTION){
try{
  Class.forName("java.sql.DriverManager");
  Connection con=(Connection)
  DriverManager.getConnection("jdbc:mysql://localhost:3306/hms","root","admin");
  java.sql.Statement stmt=(Statement) con.createStatement();
String query="UPDATE bookings set Patient_Name='"+tf2.getText()+"',Patient_Age='"+tf3.getText()+"',CNo='"+tf4.getText()+"',local_address='"+tf5.getText()+"',City='"+tf6.getText()+"',Father_Name='"+tf7.getText()+"',Blood_Group='"+tf8.getText()+"'where Patient_id="+Integer.parseInt(tf1.getText())+"";
int i=stmt.executeUpdate(query);
JOptionPane.showMessageDialog(this,"Record successfully update!");}
catch(HeadlessException | ClassNotFoundException | NumberFormatException | SQLException e){
           JOptionPane.showMessageDialog(this,e.getMessage());}} 
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String Pld=tf1.getText();
        if(Pld.isEmpty()){
            tf2.setText(null);
            tf3.setText(null);
            tf4.setText(null);
            tf5.setText(null);
            tf6.setText(null);
            tf7.setText(null);
            tf8.setText(null);
            JOptionPane.showMessageDialog(this,"Please Enter the Patient id");}
        else
        {try
            {Class.forName("java.sql.DriverManager");
                Connection con=(Connection)
                DriverManager.getConnection("jdbc:mysql://localhost:3306/hms","root","admin");
                Statement stmt=(Statement) con.createStatement();
                String query="SELECT Patient_Name,Patient_age,CNo,Local_Address,City,Father_Name,Blood_Group FROM BOOKINGS WHERE patient_id='"+Pld+"';";
                ResultSet rs=stmt.executeQuery(query);
                if(rs.next()){

                    String Patient_Name=rs.getString("Patient_Name");
                    String Patient_Age=rs.getString("Patient_Age");
                    String CNo=rs.getString("CNo");
                    String Local_Address=rs.getString("local_Address");
                    String City=rs.getString("City");
                    String Father_Name=rs.getString("Father_Name");
                    String Blood_Group=rs.getString("Blood_Group");
                    tf2.setText(Patient_Name);
                    tf3.setText(Patient_Age);
                    tf4.setText(CNo);
                    tf5.setText(Local_Address);
                    tf6.setText(City);
                    tf7.setText(Father_Name);
                     tf8.setText(Blood_Group);}
                    
                else
                JOptionPane.showMessageDialog(this,"sorry! no such Patient id");}
            catch(HeadlessException | ClassNotFoundException | SQLException e){
                JOptionPane.showMessageDialog(this,e.getMessage());}
        }

        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
int ans=JOptionPane.showConfirmDialog(this,"Do you surely want to Delete this record?");
if(ans==JOptionPane.YES_OPTION){
String P_id=tf1.getText(); 
if(P_id.isEmpty()){ 
tf2.setText(null);
tf3.setText(null);
tf4.setText(null);
tf5.setText(null);
tf6.setText(null);
tf7.setText(null);
JOptionPane.showMessageDialog(this,"Enter the Patient Id");}
else{
try {
    Class.forName("java.sql.DriverManager");
    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/hms","root","admin");
    Statement s=con.createStatement(); 
    String query="Delete FROM BOOKINGS WHERE patient_id=?";
    java.sql.Statement stmt=con.createStatement();
PreparedStatement preparedStmt=con.prepareStatement(query);
preparedStmt.setString(1,P_id);
preparedStmt.execute();
con.close();}
catch(Exception e){
JOptionPane.showMessageDialog(this,e.getMessage());}{}}}














    }//GEN-LAST:event_jButton1ActionPerformed

    private void tf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    private javax.swing.JTextField tf5;
    private javax.swing.JTextField tf6;
    private javax.swing.JTextField tf7;
    private javax.swing.JTextField tf8;
    // End of variables declaration//GEN-END:variables

}